language: python
python:
  - "3.6"
cache: pip
install:
  - pip install coverage
  - pip install coveralls
  - pip install pandas
  - pip install .
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
